security:
  ignored: /hystrix.stream
  oauth2:
    client:
      clientId: property-service
      clientSecret: buhane_property
      user-authorization-uri: http://localhost:5000/auth/oauth/authorize
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:5000/auth/users/current
      preferTokenInfo: false
      
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5433/property
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 9002

management:
  port: 9003

eureka:
  instance:
    preferIpAddress: true
    metadata-map:
      management.port: 9003