security:
  ignored: /hystrix.stream
  oauth2:
    client:
      clientId: workorder-service
      clientSecret: buhane_workorder
      user-authorization-uri: http://localhost:5000/auth/oauth/authorize
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:5000/auth/users/current
      preferTokenInfo: false
      
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/workorder
    username: postgres
    password: buhane
    driverClassName: org.postgresql.Driver

server:
  port: 9006

management:
  port: 9007

eureka:
  instance:
    metadata-map:
      management.port: 9007