spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_SERVER}/auth
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

security:
  oauth2:
    resource:
      filter-order: 3

server:
  context-path: /auth
  port: 5000

eureka:
  client:
    enabled: false