security:
  ignored: /hystrix.stream
  oauth2:
    client:
      clientId: property-service
      clientSecret: '{cipher}AQBWRw2mCA0sw44yutFW09Xm++i7xHjAyYAAQzRfygCxo3xRAPYqtvc2l4V0QYz2zyGzmZqaSHqXhvxBZrhE1OD4+8a9T/CD20biCxjD/xjZbRZMNvMLE7sv/uscXYCCkbuv8LD7UhFbwywQ0+YsVko5a17zp3G8mMdCSXX+DD0G3XbA257MdwlcV5I/8RLTbZ2dTuF2gIpa+5I5Lbzf+ROgxSwkPezRRjDXK9W2om07aTVBKic3YvZzvT6pNls6417ZAbAQtIkEXRb9ajrVftTEl0n+R253zPjSlVh8aOH1x0rcGJnq7E8arsaCu1PHvjsXwoVwfH9517rz3+GIqoggntwl9TJ9O2Vrv1K/wmsmSCE6vGN0HqRw2lX0QWudbiPavs3J7SEyF2yvFsKkrGdy'
      user-authorization-uri: http://auth-service:5000/auth/oauth/authorize
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://auth-service:5000/auth/users/current
      preferTokenInfo: false

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_SERVER}/property
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

server:
  port: 9002

management:
  port: 9003

eureka:
  instance:
    metadata-map:
      management.port: 9003
  client:
    enabled: false