security:
  ignored: /hystrix.stream
  oauth2:
    client:
      clientId: user-service
      clientSecret: '{cipher}AQAM79vZkrmmc1PFoP3Zq9bsWqnkJ3KSgMt4tEXLKqvWqjfD95KDxLmtqkyZh2DIOS6iEQjmfLXxVH8NyizAKOKRO8gc77bocfljEngIrRYnm2MaLVWLvnsuZLepDfGT3cIYKUcHFXyGAQDRsn0oYRK7LJv9jrmgD5sGx2XzgM7y3xyqKiYeidmJkQGBud7XTCy1fo13tn8lhIAHBZHNRnDejcX8jZWW+hy9UH1CcaEolBsH9bk0PFle2AoNM1cj34RXmPGJtftkgIC7zIFVy5Ui9+ScZLmQ9ZdW7gwcnT5r5qPx+S3FVNl+uEYrE0/nFZxJtzAfnBnp6L3qUb6hONqHj7hCQjkiiYy28B+1d2xQoi9O8VjQtfWSYKY3Oluyfd+rNLGGhXbT+PIACglKm6gO'
      user-authorization-uri: http://auth-service:5000/auth/oauth/authorize
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://auth-service:5000/auth/users/current
      preferTokenInfo: false

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_SERVER}/auth
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

server:
  port: 9004

management:
  port: 9005

eureka:
  instance:
    metadata-map:
      management.port: 9005
  client:
    enabled: false